-- ANTENNE.V_POSTE_DISPONIBLE source

CREATE OR REPLACE VIEW "V_POSTE_DISPONIBLE" AS
SELECT VPLC."ID",
       VPLC."NOM",
       VPLC."IDREGION",
       VPLC."IDDISTRICT",
       VPLC."IDCOMMUNE",
       VPLC."IDREGIONLIB",
       VPLC."IDDISTRICTLIB",
       VPLC."IDCOMMUNELIB",
       VPLC."IDPERSONNE",
       VPLC."NOMPERSONNE",
       VPLC."PRENOMPERSONNE"
FROM V_POSTE_LIB_COMPLET vplc
WHERE vplc.IDPERSONNE IS NULL;