INSERT INTO DEMANDE (ID, NOM) VALUES('DMDINS001', 'Partenariat');
INSERT INTO DEMANDE (ID, NOM) VALUES('DMDINS002', 'Soutien');
INSERT INTO DEMANDE (ID, NOM) VALUES('DMDINS003', 'Rencontre');

INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MEN0030', 'Poste', 'fa fa-home', NULL, 8, 1, NULL);
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MEN0031', 'Liste poste', 'fa fa-list', '/tiatanindrazana/pages/module.jsp?but=poste/poste-liste.jsp', 1, 2, 'MEN0030');
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MEN0032', 'Saisie poste', 'fa fa-plus', '/tiatanindrazana/pages/module.jsp?but=poste/poste-saisie.jsp', 2, 2, 'MEN0030');

INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MEN0020', 'Gestion des types de traitement', 'fa fa-home', NULL, 7, 1, NULL);
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MEN0021', 'Saisie types de traitement', 'fa fa-plus', '/tiatanindrazana/pages/module.jsp?but=traitement/type-traitement.jsp', 1, 2, 'MEN0020');
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MEN0022', 'Liste types de traitement', 'fa fa-list', '/tiatanindrazana/pages/module.jsp?but=traitement/liste-traitement.jsp', 2, 2, 'MEN0020');



INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMEN00020', '*', 'MEN0001', NULL, NULL, NULL, 0);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMEN00006', '*', 'MEN0020', NULL, NULL, NULL, 0);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMEN00001', '*', 'MEN0003', NULL, NULL, NULL, 0);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMEN00002', '*', 'MEN0007', NULL, NULL, NULL, 0);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMEN00003', '*', 'MEN0009', NULL, NULL, NULL, 0);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMEN00004', '*', 'MEN0013', NULL, NULL, NULL, 0);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMEN00005', '*', 'MEN0016', NULL, NULL, NULL, 0);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMENS000100', NULL, 'MEN0007', 'redacteur', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMENS000019', NULL, 'MEN0003', 'verificateur', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMENS00006', NULL, 'MEN0020', 'redacteur', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMENS00001', NULL, 'MEN0003', 'redacteur', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMENS00002', NULL, 'MEN0007', 'redacteur', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMENS00005', NULL, 'MEN0016', 'redacteur', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMENS00010', NULL, 'MEN0030', 'redacteur', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMENS000018', NULL, 'MEN0020', 'verificateur', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMENS000022', NULL, 'MEN0007', 'verificateur', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMENS000025', NULL, 'MEN0016', 'verificateur', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMENS000102', NULL, 'MEN0030', 'verificateur', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMEN00010', '*', 'MEN0030', NULL, NULL, NULL, 0);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMENSn0002', NULL, 'MEN0013', 'validateur', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT) VALUES('USRMENSn0001', NULL, 'MEN0009', 'validateur', NULL, NULL, 1);


