/*view v_personne_lib_complet_v*/
CREATE OR REPLACE VIEW "V_PERSONNE_LIB_COMPLET_V" AS
SELECT v."ID",
       v."NOM",
       v."PRENOM",
       v."TELEPHONE",
       v."JOB",
       v."SEXE",
       v."ETAT",
       v."IDATTENTE",
       v."AGE",
       v."DOMICILE",
       v."COMPTEFB",
       v."WHATSAPP",
       v."CHAMPLIBRE",
       v."MAIL",
       v."IDRESPONSABLE",
       v."TRAITEMENT",
       v."IDTYPETRAITEMENT",
       v."ETATLIB",
       v."IDATTENTELIB",
       v."REGION",
       v."DISTRICT",
       v."REGIONLIB",
       v."DISTRICTLIB",
       v."COMMUNES",
       v."COMMUNESLIB",
       v."IDRESPONSABLELIB",
       v."TYPEENTITES",
       v."IDTYPETRAITEMENTLIB",
       v."DEMANDES",
       v."DEMANDESLIB",
       v."IDPOSTELIB",
       v."IDPOSTE",
       v."CIBLE"
FROM v_personne_lib_complet v
WHERE v.etat = 11;

/*view v_personne_lib_complet*/
CREATE OR REPLACE VIEW "V_PERSONNE_LIB_COMPLET_I" AS
SELECT v."ID",
       v."NOM",
       v."PRENOM",
       v."TELEPHONE",
       v."JOB",
       v."SEXE",
       v."ETAT",
       v."IDATTENTE",
       v."AGE",
       v."DOMICILE",
       v."COMPTEFB",
       v."WHATSAPP",
       v."CHAMPLIBRE",
       v."MAIL",
       v."IDRESPONSABLE",
       v."TRAITEMENT",
       v."IDTYPETRAITEMENT",
       v."ETATLIB",
       v."IDATTENTELIB",
       v."REGION",
       v."DISTRICT",
       v."REGIONLIB",
       v."DISTRICTLIB",
       v."COMMUNES",
       v."COMMUNESLIB",
       v."IDRESPONSABLELIB",
       v."TYPEENTITES",
       v."IDTYPETRAITEMENTLIB",
       v."DEMANDES",
       v."DEMANDESLIB",
       v."IDPOSTELIB",
       v."IDPOSTE",
       v."CIBLE"
FROM v_personne_lib_complet v
WHERE v.etat = 7;

/*view V_PERSONNE_LIB_COMPLET_C*/
CREATE OR REPLACE VIEW "V_PERSONNE_LIB_COMPLET_C" AS
SELECT v."ID",
       v."NOM",
       v."PRENOM",
       v."TELEPHONE",
       v."JOB",
       v."SEXE",
       v."ETAT",
       v."IDATTENTE",
       v."AGE",
       v."DOMICILE",
       v."COMPTEFB",
       v."WHATSAPP",
       v."CHAMPLIBRE",
       v."MAIL",
       v."IDRESPONSABLE",
       v."TRAITEMENT",
       v."IDTYPETRAITEMENT",
       v."ETATLIB",
       v."IDATTENTELIB",
       v."REGION",
       v."DISTRICT",
       v."REGIONLIB",
       v."DISTRICTLIB",
       v."COMMUNES",
       v."COMMUNESLIB",
       v."IDRESPONSABLELIB",
       v."TYPEENTITES",
       v."IDTYPETRAITEMENTLIB",
       v."DEMANDES",
       v."DEMANDESLIB",
       v."IDPOSTELIB",
       v."IDPOSTE",
       v."CIBLE"
FROM v_personne_lib_complet v
WHERE v.etat = 1;

/*view V_PERSONNE_LIB_COMPLET_A*/
CREATE OR REPLACE VIEW "V_PERSONNE_LIB_COMPLET_A" AS
SELECT v."ID",
       v."NOM",
       v."PRENOM",
       v."TELEPHONE",
       v."JOB",
       v."SEXE",
       v."ETAT",
       v."IDATTENTE",
       v."AGE",
       v."DOMICILE",
       v."COMPTEFB",
       v."WHATSAPP",
       v."CHAMPLIBRE",
       v."MAIL",
       v."IDRESPONSABLE",
       v."TRAITEMENT",
       v."IDTYPETRAITEMENT",
       v."ETATLIB",
       v."IDATTENTELIB",
       v."REGION",
       v."DISTRICT",
       v."REGIONLIB",
       v."DISTRICTLIB",
       v."COMMUNES",
       v."COMMUNESLIB",
       v."IDRESPONSABLELIB",
       v."TYPEENTITES",
       v."IDTYPETRAITEMENTLIB",
       v."DEMANDES",
       v."DEMANDESLIB",
       v."IDPOSTELIB",
       v."IDPOSTE",
       v."CIBLE"
FROM v_personne_lib_complet v
WHERE v.etat = 0;